# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
# socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
redir-port: 7891

# 透明代理端口 Transparent proxy server port (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# 允许局域网的连接（可用来共享代理）----false true
allow-lan: false

# -----仅在将allow-lan设置为true时适用----------
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: debug

# Clash.Meta特性
# 统一延迟
unified-delay: true
# TCP并发
tcp-concurrent: true

hosts:
   'router.internal': 10.0.0.1
   'storage.internal': 10.0.0.11

dns:
  enable: true
  prefer-h3: true
  cache-algorithm: arc
  listen: '0.0.0.0:1053'
  ipv6: true
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    # https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
    # === LAN ===
    - '+.lan'
    - '+.localdomain'
    - '+.example'
    - '+.invalid'
    - '+.localhost'
    - '+.test'
    - '+.local'
    - '+.home.arpa'
    - '+.internal'
    # === Windows 10 Connnect Detection ===
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    # === NTP Service ===
    - 'ntp.*.com'
    - 'time.*.com'
    - time-ios.apple.com
    - time-macos.apple.com
    - '+.pool.ntp.org'
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    #- system
    - 'https://doh.360.cn/dns-query'
    - 'https://dns.alidns.com/dns-query'
  fallback:
    - 'https://mozilla.cloudflare-dns.com/dns-query'
    - 'https://dns.google/dns-query'
  proxy-server-nameserver:
    #- system
    - 'https://dns.alidns.com/dns-query'
    - 'https://doh.pub/dns-query'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      # https://en.wikipedia.org/wiki/Reserved_IP_addresses
      - ::/128
      - ::1/128
      - 2001::/32
      - 0.0.0.0/8
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 240.0.0.0/3
      - 255.255.255.255/32
    domain:
      # 一定要对齐，不然会出BUG
      # 复制到Windows记事本时，前方打4个空格
############# Proxy.list
# 谷歌中国
      - '+.gstatic.cn'
      - '+.googleapis.cn'
      - '+.google.cn'
# 微软中国
      - '+.msn.cn'
############# AI.list
# OpenAI
      - '+.ai.com'
      - '+.auth0.com'
      - '+.chat.com'
      - '+.chatgpt.com'
      - '+.featuregates.org'
      - '+.oaistatic.com'
      - '+.oaiusercontent.com'
      - '+.openai.com'
      - '+.sentry.io'
      - '+.sora.com'
# X grok
      - '+.grok.com'
############# Common.list
### A
# Adblock Plus
      - '+.adblockplus.org'
# ASUS
      - '+.asus.com'
# AWS
      - '+.aws'
      - '+.aws.com'
      - '+.amazon'
      - '+.amazon.com'
      - '+.amazonaws.com'
      - '+.cloudfront.net'
# Akamai
      - '+.akadns.net'
      - '+.akamai.net'
      - '+.akamaized.net'
      - '+.akamaiedge.net'
      - '+.akamaihd.net'
      - '+.akamaistream.net'
      - '+.edgekey.net'
# Apkpure
      - '+.apkpure.com'
      - '+.cdnpure.com'
      - '+.pureapk.com'
      - '+.winudf.com'
# Adidas
      - '+.adidas.com'
### B
### C
# Cloudflare
      - '+.cf-ipfs.com'
      - '+.cloudflare-dns.com'
      - '+.cloudflare-ech.com'
      - '+.cloudflare-ipfs.com'
      - '+.cloudflare-quic.com'
      - '+.cloudflare.com'
      - '+.cloudflare.net'
      - '+.cloudflareaccess.com'
      - '+.cloudflareapps.com'
      - '+.cloudflarebolt.com'
      - '+.cloudflareclient.com'
      - '+.cloudflareinsights.com'
      - '+.cloudflaremirrors.com'
      - '+.cloudflareok.com'
      - '+.cloudflarepreview.com'
      - '+.cloudflareresolve.com'
      - '+.cloudflaressl.com'
      - '+.cloudflarestatus.com'
      - '+.cloudflarestorage.com'
      - '+.cloudflarestream.com'
      - '+.cloudflaretest.com'
      - '+.cloudflarewarp.com'
      - '+.every1dns.net'
      - '+.pacloudflare.com'
      - '+.pages.dev'
      - '+.trycloudflare.com'
      - '+.videodelivery.net'
      - '+.warp.plus'
      - '+.workers.dev'
# Contentful
      - '+.contentful.com'
      - '+.ctfassets.net'
### D
# Duckduckgo
      - '+.duckduckgo.com'
# 毒奶
      - '+.limbopro.com'
# DeepL
      - '+.deepl.com'
# Daum（Kakao 运营）
      - '+.daumcdn.net'
# Docker
      - '+.docker.com'
      - '+.docker.io'
      - '+.dockerhub.com'
      - '+.compose-spec.io'
# Developer
      - '+.apache.org'
      - '+.elastic.co'
      - '+.elastic.com'
      - '+.gcr.io'
      - '+.gitlab.com'
      - '+.gitlab.io'
      - '+.jitpack.io'
      - '+.maven.org'
      - '+.medium.com'
      - '+.mvnrepository.com'
      - '+.quay.io'
      - '+.redhat.com'
      - '+.sonatype.org'
      - '+.sourcegraph.com'
      - '+.spring.io'
      - '+.spring.net'
      - '+.stackoverflow.com'
### E
### F
# Fastly
      - '+.fastly.net'
      - '+.fastly.com'
      - '+.fastly-edge.com'
# Edgecast
      - '+.edgecastcdn.net'
# Foxit Software
      - '+.foxit.com'
      - '+.connectedpdf.com'
### G
# Google
      - '+.1e100.net'
      - '+.android.com'
      - '+.g.co'
      - '+.ggpht.com'
      - '+.goo.gl'
      - '+.google.com'
      - '+.googlevideo.com'
      - '+.goog'
      - '+.google'
      - '+.googleusercontent.com'
      - '+.googleapis.com'
      - '+.gstatic.com'
      - '+.gmail.com'
      - '+.gvt0.com'
      - '+.gvt1.com'
      - '+.gvt2.com'
      - '+.gvt3.com'
      - '+.gvt5.com'
      - '+.gvt4.com'
      - '+.gvt6.com'
      - '+.gvt7.com'
      - '+.gvt9.com'
      - '+.xn--ngstr-lra8j.com'
      - '+.youtu.be'
      - '+.youtube-nocookie.com'
      - '+.youtube.com'
      - '+.yt.be'
      - '+.ytimg.com'
      - '+.recaptcha.net'
      - '+.withgoogle.com'
# Github
      - '+.github.com'
      - '+.github.io'
      - '+.githubassets.com'
      - '+.githubcopilot.com'
      - '+.githubusercontent.com'
# Gigabyte
      - '+.aorus.com'
      - '+.gigabyte.com'
### H
# Hcaptcha
      - '+.hcaptcha.com'
### I
# Internet Archive
      - '+.archive.org'
# IMDB
      - '+.imdb.com'
      - '+.media-imdb.com'
# Imgur 图床
      - '+.imgur.com'
      - '+.imgurinc.com'
# ITDOG
      - '+.itdog.plus'
# IPLEAK
      - '+.ipleak.net'
# ImmortalWrt
      - '+.immortalwrt.org'
### J
# jQuery,a fast, small, and feature-rich JavaScript library
      - '+.jquery.com'
### K
### L
# Landrop
      - '+.landrop.app'
### M
# Microsoft
      - '+.ms'
      - '+.1drv.com'
      - '+.ax-msedge.net'
      - '+.azure.com'
      - '+.azure.net'
      - '+.azureedge.net'
      - '+.azurewebsites.net'
      - '+.bing.com'
      - '+.bing.net'
      - '+.bingapis.com'
      - '+.edgesuite.net'
      - '+.footprintdns.com'
      - '+.linkedin.com'
      - '+.live.com'
      - '+.live.net'
      - '+.microsoft'
      - '+.microsoft.com'
      - '+.microsoft.net'
      - '+.microsoftapp.net'
      - '+.microsoftonline.com'
      - '+.microsoftpersonalcontent.com'
      - '+.microsofttranslator.com'
      - '+.microsoft-falcon.io'
      - '+.msauth.net'
      - '+.msftauthimages.net'
      - '+.msecnd.net'
      - '+.msedge.net'
      - '+.msftauth.net'
      - '+.msftstatic.com'
      - '+.msn.com'
      - '+.office.com'
      - '+.office.net'
      - '+.office365.com'
      - '+.onedrive.com'
      - '+.onenote.net'
      - '+.sharepoint.com'
      - '+.sharepointonline.com'
      - '+.skype.com'
      - '+.windows.com'
      - '+.windows.net'
# Visual Studio Code
      - '+.vscode-cdn.net'
      - '+.vscode-unpkg.net'
      - '+.vscodeedu.app'
      - '+.vscode.dev'
      - '+.exp-tas.com'
      - '+.visualstudio.com'
      - '+.vscodeedu.com'
# Meta(Facebook Instagram)
      - '+.cdninstagram.com'
      - '+.facebook.com'
      - '+.fbcdn.com'
      - '+.fbcdn.net'
      - '+.instagram.com'
# Mozilla Corporation
      - '+.bugzilla.org'
      - '+.extensionworkshop.com'
      - '+.firefox.com'
      - '+.firefoxusercontent.com'
      - '+.mozillademos.org'
      - '+.mozit.cloud'
      - '+.getpocket.com'
      - '+.pocket-image-cache.com'
      - '+.seamonkey-project.org'
      - '+.thunderbird.net'
      - '+.rustup.rs'
      - '+.rust-lang.org'
      - '+.crates.io'
      - '+.docs.rs'
      - '+.mofoprod.net'
      - '+.mozaws.net'
      - '+.mozgcp.net'
      - '+.mozilla.com'
      - '+.mozilla.community'
      - '+.mozilla.net'
      - '+.mozilla.org'
# 名字生成器
      - '+.qmsjmfb.com'
# 妙佑医疗
      - '+.mayoclinic.org'
      - '+.mayoclinichealthsystem.org'
# MediSearch
      - '+.medisearch.io'
### N
# Notion
      - '+.notion-static.com'
      - '+.notion.com'
      - '+.notion.new'
      - '+.notion.site'
      - '+.notion.so'
# NVIDIA
      - '+.nvidia.com'
# NIKE
      - '+.nike.com'
      - '+.nike.com.hk'
      - '+.nikecdn.com'
      - '+.nikecloud.com'
      - '+.niketracking.com'
      - '+.static-nike.com'
      - '+.swoo.sh'
      - '+.swoosh.com'
### O
# Ookla
      - '+.downdetector.com'
      - '+.downdetectorapi.com'
# OMDb API
      - '+.omdbapi.com'
# OpenWrt
      - '+.openwrt.org'
### P
# Pinterest
      - '+.pinimg.com'
      - '+.pinterest.com'
# Pixiv
      - '+.pixiv.net'
      - '+.pximg.net'
# Porn
      - '+.8teenxxx.com'
      - '+.ahcdn.com'
      - '+.bcvcdn.com'
      - '+.bongacams.com'
      - '+.chaturbate.com'
      - '+.dditscdn.com'
      - '+.livejasmin.com'
      - '+.phncdn.com'
      - '+.phprcdn.com'
      - '+.pornhub.com'
      - '+.pornhubpremium.com'
      - '+.rdtcdn.com'
      - '+.redtube.com'
      - '+.sb-cd.com'
      - '+.spankbang.com'
      - '+.t66y.com'
      - '+.xhamster.com'
      - '+.xnxx-cdn.com'
      - '+.xnxx.com'
      - '+.xvideos-cdn.com'
      - '+.xvideos.com'
      - '+.ypncdn.com'
# PeeringDB
      - '+.peeringdb.com'
### Q
# Quora
      - '+.quora.com'
# Quantumult X APP
      - '+.quantumult.app'
### R
# Reddit
      - '+.redd.it'
      - '+.reddit.com'
      - '+.redditmedia.com'
      - '+.redditstatic.com'
# RoboForm
      - '+.roboform.com'
# RevenueCat
      - '+.revenuecat.com'
### S
# Ookla Speedtest
      - '+.speedtest.net'
### T
# Tor
      - '+.torproject.org'
# Twilio
      - '+.twilio.com'
# Transcend CDN
      - '+.transcend-cdn.com'
### U
# UNPKG
      - '+.unpkg.com'
### V
# V2EX
      - '+.v2ex.com'
### W
# Wikipedia 维基百科
      - '+.mediawiki.org'
      - '+.wikibooks.org'
      - '+.wikidata.org'
      - '+.wikileaks.org'
      - '+.wikimedia.org'
      - '+.wikinews.org'
      - '+.wikipedia.org'
      - '+.wikiquote.org'
      - '+.wikisource.org'
      - '+.wikiversity.org'
      - '+.wikivoyage.org'
      - '+.wiktionary.org'
### X
# Xmind
      - '+.xmind.app'
# X(Twitter)
      - '+.t.co'
      - '+.twimg.com'
      - '+.twitter.com'
      - '+.x.com'
### Y
# Yandex
      - '+.yandex.net'
      - '+.yastatic.net'
### Z
# zxinc.org（实用工具库）
      - '+.zxinc.org'
### 0
### 1
# 1Password
      - '+.1password.com'
      - '+.1passwordservices.com'
### 2
### 3
### 4
### 5
### 6
### 7
### 8
### 9
### 其他
### 特殊
## 证书验证
# Amazon Trust Services
      - '+.amazontrust.com'
# Comodo UserTrust
      - '+.usertrust.com'
# DigiCert
      - '+.digicert.com'
# Let's Encrypt
      - '+.lencr.org'
# ocsp-certum
      - '+.ocsp-certum.com'
# Sectigo
      - '+.sectigo.com'
## CDN
# jsDelivr
      - '+.jsdelivr.com'
      - '+.jsdelivr.net'
# BootstrapCDN
      - '+.bootstrapcdn.com'
# IP测试
# ipify API
      - '+.ipify.org'
# ip.sb
      - '+.ip.sb'
# lvhai.org
      - '+.lvhai.org'
# IP-API
      - '+.ip-api.com'
# IPPure
      - '+.ippure.com'
# IPinfo
      - '+.ipinfo.io'
############# Apple.list
# Apple
      - '+.apple'
      - '+.aaplimg.com'
      - '+.apple-cloudkit.com'
      - '+.apple-dns.net'
      - '+.apple-livephotoskit.com'
      - '+.apple-mapkit.com'
      - '+.apple.co'
      - '+.apple.com'
      - '+.apple.news'
      - '+.appstore.com'
      - '+.apzones.com'
      - '+.icloud-content.com'
      - '+.icloud.com'
      - '+.itunes.com'
      - '+.me.com'
      - '+.mzstatic.com'
############# Communication.list
# Telegram
      - '+.cdn-telegram.org'
      - '+.t.me'
      - '+.tdesktop.com'
      - '+.telegra.ph'
      - '+.telesco.pe'
      - '+.telegram.me'
      - '+.telegram.org'
############# GamingPlatform.list
# 反作弊平台
# EAC
      - '+.easy.ac'
      - '+.eac-cdn.com'
# BattlEye
      - '+.battleye.com'
# Bethesda 贝塞斯达
      - '+.beth.games'
      - '+.bethesda.net'
      - '+.bethesdagamestudios.com'
      - '+.bethsoft.com'
# Blizzard
      - '+.battle.net'
      - '+.battlenet.com'
      - '+.blizzard.com'
# Discord
      - '+.discord.co'
      - '+.discord.com'
      - '+.discord.gg'
      - '+.discord.media'
      - '+.discordapp.com'
      - '+.discordapp.net'
# EA游戏平台 https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
      - '+.ea.com'
      - '+.origin.com'
# 聊天/好友服务
      - '+.tnt-ea.com'
# EPIC 虚幻游戏平台
      - '+.epicgames.com'
      - '+.epicgames.dev'
      - '+.helpshift.com'
      - '+.paragon.com'
      - '+.unrealengine.com'
# GOG游戏平台
      - '+.gog.com'
      - '+.gog-statics.com'
      - '+.gog.qtlglb.com'
# Hitman
      - '+.ioi.dk'
      - '+.hitman.io'
# Sony https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
      - '+.playstation.com'
      - '+.playstationnetwork.com'
      - '+.sony.com'
      - '+.sonyentertainmentnetwork.com'
      - '+.playstation.net'
# Steam 游戏平台 https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/Steam.list https://steamcommunity.com/discussions/forum/1/154644349172660302/
      - '+.steam-api.com'
      - '+.steam-chat.com'
      - '+.steamcommunity.com'
      - '+.steamgames.com'
      - '+.steampowered.com'
      - '+.steamstatic.com'
      - '+.steamusercontent.com'
      - '+.valvesoftware.com'
# Nintendo 任天堂 https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/Nintendo.list
      - '+.nintendo.co.jp'
      - '+.nintendo.com'
      - '+.nintendo.net'
      - '+.nintendowifi.net'
# R星游戏
      - '+.rockstargames.com'
# Ubisoft
      - '+.ubisoft.com'
      - '+.uplay.com'
      - '+.ubi.com'
      - '+.ubi.li'
# Xbox https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Xbox.list
      - '+.xbox.com'
      - '+.xboxab.com'
      - '+.xboxab.net'
      - '+.xboxlive.com'
      - '+.xboxservice.com'
      - '+.xboxservices.com'
      - '+.gamepass.com'
# Valorant
      - '+.playvalorant.com'
############# MediaStream.list
# SoundCloud https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SoundCloud.list
      - '+.p-cdn.us'
      - '+.sndcdn.com'
      - '+.soundcloud.com'
# Spotify https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
      - '+.pscdn.co'
      - '+.scdn.co'
      - '+.spoti.fi'
      - '+.spotify.com'
      - '+.spotifycdn.com'
      - '+.spotifycdn.net'
# Netflix https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
      - '+.netflix.com.edgesuite.net'
      - '+.fast.com'
      - '+.netflix.com'
      - '+.netflix.net'
      - '+.netflixdnstest0.com'
      - '+.netflixdnstest1.com'
      - '+.netflixdnstest2.com'
      - '+.netflixdnstest3.com'
      - '+.netflixdnstest4.com'
      - '+.netflixdnstest5.com'
      - '+.netflixdnstest6.com'
      - '+.netflixdnstest7.com'
      - '+.netflixdnstest8.com'
      - '+.netflixdnstest9.com'
      - '+.nflxext.com'
      - '+.nflximg.com'
      - '+.nflximg.net'
      - '+.nflxso.net'
      - '+.nflxvideo.net'
# Twitch
      - '+.ext-twitch.tv'
      - '+.jtvnw.net'
      - '+.ttvnw.net'
      - '+.twitch.tv'
      - '+.twitchcdn.net'
# TikTok https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
      - 'lf16-effectcdn.byteeffecttos-g.com'
      - 'lf16-pkgcdn.pitaya-clientai.com'
      - 'p16-tiktokcdn-com.akamaized.net'
      - 'trae-api-sg.mchost.guru'
      - '+.byteintlapi.com'
      - '+.byteoversea.com'
      - '+.ibytedtos.com'
      - '+.ibyteimg.com'
      - '+.ipstatp.com'
      - '+.marscode.com'
      - '+.muscdn.com'
      - '+.musical.ly'
      - '+.sgpstatp.com'
      - '+.snssdk.com'
      - '+.tik-tokapi.com'
      - '+.tiktok.com'
      - '+.tiktokcdn-us.com'
      - '+.tiktokcdn.com'
      - '+.tiktokv.com'
      - '+.tiktokv.us'
      - '+.trae.ai'
      - '+.ttwebview.com'
      - '+.ttwstatic.com'
    nameserver-policy:
      '+.msftconnecttest.com': 'https://dns.alidns.com/dns-query'
      '+.msftncsi.com': 'https://dns.alidns.com/dns-query'