[custom]
; 详细
; 适合所有设备使用
; Name.SS/V2ray/Trojan.Clash.Main
; Name.SS/V2ray/Trojan.Clash.Main.yaml
; 推荐更新时间 1天=24小时=1440分钟=86400秒 7天=10080分钟=604800秒
; 订阅转换 https://acl4ssr-sub.github.io/

; [ruleset] 部分 #4 从本地或 url 获取规则片段
; 局域网
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/LAN.list
; 门户网站
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/Portal.list
; 直连（高优先级）
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/Direct.list
; 代理（高优先级）
ruleset=✅ 代理,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/Proxy.list
; 网站净化
ruleset=🚫 净化,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/Reject.list
; 软件净化
ruleset=🚫 净化,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/RejectSoftware.list
; Apple 推送通知服务 (APNS)
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/ApplePush.list
; 直连端口
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/Port.list
; 直连网站
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Mainland/Normal.list
; 特殊资源
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Mainland/Special.list
; NTP
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Uni/NTP.list
; 用于回退的DNS
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Mainland/FallbackDNS.list
; 游戏下载
ruleset=DIRECT,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/Download.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GameDownload.list
; 流媒体平台
ruleset=💽 视听,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/MediaStream.list
; AI(美国)
ruleset=📰 通讯,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/AI.list
; 苹果公司
ruleset=🍎 苹果,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/Apple.list
; 游戏平台
ruleset=🎮 游戏,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/GamingPlatform.list
; 通讯服务
ruleset=📰 通讯,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/Communication.list
; 常用网站
ruleset=✅ 代理,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/Common.list
; DNS
ruleset=✅ 代理,https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Ruleset/Web/Oversea/DNS.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=✅ 代理,[]FINAL

; [proxy_group] 部分
; https://github.com/tindy2013/subconverter/blob/master/README-cn.md
custom_proxy_group=✅ 代理`select`.*
custom_proxy_group=💽 视听`select`[]✅ 代理`新加坡|SG|Singapore`台湾|TW|Taiwan`.*
custom_proxy_group=📰 通讯`select`[]✅ 代理`美国|US|United States`.*
custom_proxy_group=🍎 苹果`select`[]✅ 代理`美国|US|United States`.*
custom_proxy_group=🎮 游戏`select`[]✅ 代理`香港|HK|HongKong|Hong Kong`.*
custom_proxy_group=🚫 净化`select`[]REJECT`[]DIRECT
;custom_proxy_group=♻️ 自动`url-test`(^(?=.*(?:HK|US))(?!.*(?:AUS|RUS)).*$)`http://mt0.google.com/generate_204`300,5,200

; 外部配置 用于自定义规则的选项 会覆盖 主程序目录中的配置文件 里的内容
enable_rule_generator=true

; [ruleset] 部分 #2 覆盖原有规则，即 [common] 中 xxx_rule_base 中的内容，设置为 true 时打开，默认为 false
; clash_rule_base :生成的 Clash 配置文件模板。支持 本地文件 和 在线URL , [common] 部分 #13
overwrite_original_rules=true

; [common] 部分 #13 生成的 Clash 配置文件模板。支持 本地文件 和 在线URL
clash_rule_base=https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/GeneralConfig.yml

; [common] 部分 #7 仅保留匹配到的节点，支持正则匹配
;include_remarks=(?<=美).*(BGP|GIA|IPLC)

; [common] 部分 #8 排除匹配到的节点，支持正则匹配
exclude_remarks=(Panel|Traffic|Expire|使用|试用|官网|流量|剩余|套餐|到期|充值|重置|续费|时间|日期|注意|不合适)
;exclude_remarks=(.*流量.*剩.*天)
;exclude_remarks=(■等级警报■)
;exclude_remarks=(\[限速\])
;exclude_remarks=(\[游戏专用\])

; [emojis] 部分 #1 是否在节点名称前加入下面自定义的 Emoji，设置为 true 时打开，默认为 true
add_emoji=false
; [emojis] 部分 #2 是否移除原有订阅中存在的 Emoji，设置为 true 时打开，默认为 true
remove_old_emoji=false
; [emojis] 部分 #3 更多 https://github.com/loongfzs/subconverter/blob/main/README.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
;emoji=(流量|时间|应急),🏳️‍🌈
;emoji=阿根廷,🇦🇷
;你在外部配置中定义了以上两个 Emoji,那么本程序只会匹配以上两个 Emoji，不再使用 主程序目录中配置文件 中所定义的 国别 Emoji

; [node_pref] 部分 #1 为节点打开 UDP 模式，设置为 true 时打开，默认为 false
;-   当不清楚机场的设置时**请勿调整此项**。
udp_flag=true

; [node_pref] 部分 #2 为节点打开 TFO (TCP Fast Open) 模式，设置为 true 时打开，默认为 false
;-   当不清楚机场的设置时**请勿调整此项**。
;tcp_fast_open_flag=true

; [node_pref] 部分 #3 关闭 TLS 节点的证书检查，设置为 true 时打开，默认为 false
;-   **请勿随意将此设置修改为 true**
skip_cert_verify_flag=false

; [node_pref] 部分 #8 在 header 里的加入流量信息 (读取后可以显示流量信息通知)，设置为 true 时打开，默认为 true
append_sub_userinfo=true

; [common] 部分 #22 节点名称是否需要加入属性，设置为 true 时在节点名称前加入 [SS] [SSR] [VMess] 以作区别
append_proxy_type=false

; [node_pref] 部分 #5 对生成的订阅中的节点按节点名进行 A-Z 的排序，设置为 true 时打开，默认为 false
sort_flag=false

; [node_pref] 部分 #7 排除当前 target= 不支持的节点类型，设置为 true 时打开，默认为 false
;-   可以考虑设置为 true，从而在**一定程度上避免出现兼容问题**
filter_deprecated_nodes=false

; [node_pref] 部分 #9 启用 Clash 的新区块名称 (proxies, proxy-groups, rules)，设置为 true 时打开，默认为 true
;Clash 内核在 v0.19.0 版本时开始启用新区块名称，当前已广泛使用 v0.19.0 及以上的版本，除非您确定正在使用极为古老的版本，否则请勿关闭。
clash_use_new_field_name=true

; [common] 部分 #19 更新 外部配置文件 时是否使用代理
;填写 NONE 或者空白禁用，或者填写 SYSTEM 使用系统代理
;支持 HTTP 或 SOCKS 代理(http:// https:// socks4a:// socks5://)
;支持 CORS 代理(cors：)，详细参见cors-anywhere、cloudflare-cors-anywhere等
proxy_config=SYSTEM

; [node_pref] 部分 #11 
;重命名节点，支持正则匹配
;使用方式：原始命名@重命名
;可以使用自定义的 js 函数进行重命名
;具体细节参照 [common] 部分filter_script中的介绍
;rename=Test-(.*?)-(.*?)-(.*?)\((.*?)\)@\1\4x测试线路_自\2到\3
;rename=\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?@$1x
;rename_node=IPLC@专线
;rename_node=RELAY@中转
;rename_node=!!import:https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Snippets/rename_node.txt
;rename_node=!!import:https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Snippets/rename_node_simple.txt
;rename_node=!!import:https://raw.githubusercontent.com/loongfzs/Clash-Config/main/Clash/Snippets/rename_node_extend.txt

; [managed_config] 部分 #3 托管配置更新间隔，确定配置将更新多长时间，单位为秒
config_update_interval = 14400